# https://github.com/katze225/Katze-AntiBot

# Проверки
check:

  # Проверка на proxy
  proxy:
    enabled: true
    list:
      - "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt"
      - "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt"
      - "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt"
      - "https://api.openproxylist.xyz/socks5.txt"
      - "https://api.openproxylist.xyz/socks4.txt"
      - "https://api.openproxylist.xyz/http.txt"
      - "https://tcpshield.com/blocklist.txt"
      - "https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks4.txt"
      - "https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks5.txt"
      - "https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/http.txt"
      - "https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/https.txt"

  # Title капча
  captcha:
    enabled: true
    # Размер капчи
    length: 4
    # Время в секундах для решения капчи
    time: 30
    # Попытки для решения капчи
    attempts: 3

    # Запутывать ли капчу
    confused: true

    # Сколько времени в минутах игроку не нужно будет проходить капчу
    whitelist-time: 120
    # Игроки которым не нужно будет проходить капчу
    whitelist-players: ["Katze225", "Steve", "Gamer001"]

    # Эффект слепоты
    blindness: true

# Сообщения плагина
message:
  use-proxy: "&cВы используете прокси!"
  already-online: "&cВы уже находитесь на сервере!"

  captcha-kick: "&cВы не прошли капчу!"
  captcha-title: "&a{code}"
  captcha-subtitle: "&fВведите код который отображается выше."
  captcha-chat-notify: "&fВведите код, чтобы пройти капчу."
  captcha-chat-deny: "&cНеправильный код, у вас осталось {attempts} попытки."
  captcha-chat-well: "&aВы успешно решили капчу, удачной игры!"
  captcha-chat-block: "&cПройдите капчу, чтобы делать это!"

  placeholder-code: "&a{code}"
  placeholder-well: "&aВы решили капчу"

  no-permission: "&cУ вас недостаточно прав для использования этой команды!"

  command-usage: "&fИспользуйте: &a/katze-antibot <stats>"
  command-stats: "\n&fСтатистика:\n&fИгроков на капче: &e{onCaptcha}\n&fИгроков прошёдших капчу: &a{wellCaptcha}\n&fИгроков проваливших капчу: &c{denyCaptcha}\n&r"


