# https://github.com/katze225/Katze-AntiBot

# Checks
check:

  # Check null LOCALE
  locale:
    enabled: true

  # Check null VIEW_DISTANCE
  view-distance:
    enabled: true

  # Check proxy
  proxy:
    enabled: true
    list:
      - "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt"
      - "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt"
      - "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt"
      - "https://api.openproxylist.xyz/socks5.txt"
      - "https://api.openproxylist.xyz/socks4.txt"
      - "https://api.openproxylist.xyz/http.txt"
      - "https://tcpshield.com/blocklist.txt"

  # Title captcha
  captcha:
    enabled: true
    # Chars on captcha
    chars: "1234567890"
    # Char length
    length: 6
    # In sec
    time: 30
    # Attempts for captcha
    attempts: 3
    # Confuses captcha
    confused: true
    # Indicate in minutes; if 0, it means disabled
    whitelist-time: 120
    # Give blindness effect
    give-blindness: true

message:
  null-locale: "&cПохоже вы бот, у вас отсутствует пакет локализации"
  null-view_distance: "&cПохоже вы бот, у вас отсутствует пакет дистанции прорисовки"
  use-proxy: "&cВы используете прокси или впн!"
  captcha-kick: "&cВы не прошли капчу!"
  captcha-title: "&a{code}"
  captcha-subtitle: "&fВведите код который отображается выше."
  captcha-chat-notify: "&fВведите код, чтобы пройти капчу."
  captcha-chat-deny: "&cНеправильный код, у вас осталось {attempts} попытки."
  captcha-chat-well: "&aВы успешно решили капчу, удачной игры!"
  captcha-chat-block: "&cПройдите капчу, чтобы делать это!"

  placeholder-code: "&a{code}"
  placeholder-well: "&aВы решили капчу"

  no-permission: "&cУ вас недостаточно прав для использования этой команды!"

  command-usage: "&fИспользуйте: &a/katze-antibot <reload/stats>"
  command-reload: "&aПлагин успешно перезагружен!"
  command-stats: "\n&fСтатистика:\n&fИгроков на капче: &e{onCaptcha}\n&fИгроков прошёдших капчу: &a{wellCaptcha}\n&fИгроков проваливших капчу: &c{denyCaptcha}\n&r"


