name: Katze-AntiBot
version: '${project.version}'
main: me.katze.AntiBot
api-version: '1.16'
authors: [katze225]
description: AntiBot для вашего сервера minecraft.
website: https://github.com/katze225
softdepend: [PlaceholderAPI]